---
- name: Check if users exist
  getent:
    database: passwd
    key: "{{ item }}"
  register: users_check
  failed_when: false
  loop: "{{ users | map(attribute='name') | list }}"

- name: Create new users
  user:
    home: "{{ item.home | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    name: "{{ item.name }}"
    state: present
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | join(',') }}"
    password: "{{ item.password | default(omit) }}"
  loop: "{{ users }}"
  when: "'{{ item.name }}' not in users_check.results | map(attribute='key') | list"

- name: Add SSH keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
  when: item.ssh_key is defined

- name: Manage sudoers file entries
  copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.sudoers_content }}"
    mode: '0440'
  loop: "{{ users }}"
  when: item.sudoers_content is defined

- name: Delete users
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ delete_users }}"

- name: Disable users
  user:
    name: "{{ item }}"
    shell: "/sbin/nologin"
  loop: "{{ disable_users }}"

- name: Change user shells
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
  loop: "{{ change_shells }}"
