pipeline {
    agent any
    
    options {
        buildDiscarder(logRotator(numToKeepStr: '7'))
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        timestamps()
    }
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Enter the name of the branch')
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning repository..."
                checkout([$class: 'GitSCM', branches: [[name: "${params.BRANCH_NAME}"]], userRemoteConfigs: [[url: 'https://github.com/DEL-ORG/a1franklin.git']]])
            }
        }
        stage('Stage 1') {
            steps {
                sh '''
                     mkdir gym
                     rm -rf gym
                '''
            }
        }
        stage('Stage 2') {
            steps {
                sh '''
                    touch file2
                    rm file2
                '''
            }
        }
    }

    post {
        always {
            success {
                slackSend color: '#2EB67D',
                channel: 'a1franklin', 
                message: "*Revive Project Build Status*" +
                "\n Project Name: Revive-project" +
                "\n Job Name: ${env.JOB_NAME}" +
                "\n Build number: ${currentBuild.displayName}" +
                "\n Build Status : *SUCCESS*" +
                "\n Build url : ${env.BUILD_URL}"
            }
            failure {
                slackSend color: '#E01E5A',
                channel: 'a1franklin',  
                message: "*Revive Project Build Status*" +
                "\n Project Name: Revive-project" +
                "\n Job Name: ${env.JOB_NAME}" +
                "\n Build number: ${currentBuild.displayName}" +
                "\n Build Status : *FAILED*" +
                "\n Build User : *Franklin*" +
                "\n Action : Please check the console output to fix this job IMMEDIATELY" +
                "\n Build url : ${env.BUILD_URL}"
            }
            //unstable {
            //    slackSend color: '#ECB22E',
            //    channel: 'revive', 
            //    message: "*Revive Project Build Status*" +
            //    "\n Project Name: Revive-project" +
            //    "\n Job Name: ${env.JOB_NAME}" +
            //    "\n Build number: ${currentBuild.displayName}" +
            //    "\n Build Status : *UNSTABLE*" +
            //    "\n Action : Please check the console output to fix this job IMMEDIATELY" +
            //    "\n Build url : ${env.BUILD_URL}"
            //}  
        }
    }
}
