---
 vars:
    users:
      - name: jsmith
        home: "/home/jsmith"
        comment: John Smith
        uid: 1040
        shell: /bin/bash
        groups: ['admin', 'users']
        ssh_key: "ssh-rsa AAAA..."
        sudoers_content: "john ALL=(ALL) NOPASSWD:ALL"
      - name: bjones
        comment: barbara jones
        uid: 1060
        shell: /bin/zsh
        groups: ['users']
        ssh_key: "ssh-rsa BBBB..."
      - name: sangelina
    delete_users:
      - olduser
    disable_users:
      - tempuser
    change_shells:
      - name: john
        shell: /bin/zsh
