pipeline {
    agent any
    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '3', numToKeepStr: '3'))
        disableConcurrentBuilds()
        timeout(time: 1, unit: 'HOURS')
        timestamps()
    }

    triggers {
        githubPush() // This will trigger the pipeline on GitHub push events
    }

    stages {
        stage('Webhook') {
            steps {
                script {
                    // Checkout code from GitHub
                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/main']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [],
                        userRemoteConfigs: [[url: 'https://github.com/DEL-ORG/a1franklin.git']]
                    ])
                }
            }
        }

        stage('Test') {
            steps {
                sh '''
                kubectl 
                pwd
                uname -r 
                touch eric
                '''
            }
        }

        stage('Validate') {
            steps {
                sh 'pwd'
            }
        }

        stage('Scan') {
            steps {
                sh 'pwd'
            }
        }

        stage('Build') {
            steps {
                sh '''
                echo "FROM httpd:2.4" > Dockerfile
                docker build -t eric .
                docker images
                '''
            }
        }

        stage('Push') {
            steps {
                sh 'pwd'
            }
        }

        stage('Deploy') {
            steps {
                sh 'pwd'
            }
        }
    }


    post {
        always {
            script {
                // Add your post-build actions here
            }
        }
    }
}
